package com.discord.tti_manager;

import co.discord.media_engine.C2689b;
import com.facebook.fbreact.specs.NativeTimingSpec;
import java.util.ArrayList;
import java.util.List;
import kotlin.Metadata;
import kotlin.jvm.internal.C9612q;

@Metadata(m14358d1 = {"\u0000>\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0002\b\u0006\n\u0002\u0010!\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\t\n\u0002\b\u0004\bÆ\u0002\u0018\u00002\u00020\u0001:\u0001\u0019B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J&\u0010\r\u001a\"\u0012\f\u0012\n \u000f*\u0004\u0018\u00010\f0\f0\u000ej\u0010\u0012\f\u0012\n \u000f*\u0004\u0018\u00010\f0\f`\u0010J.\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u00142\b\b\u0002\u0010\u0015\u001a\u00020\u00162\n\b\u0002\u0010\u0017\u001a\u0004\u0018\u00010\u00142\b\b\u0002\u0010\u0018\u001a\u00020\u0004R&\u0010\u0005\u001a\u00020\u00042\u0006\u0010\u0003\u001a\u00020\u00048F@FX\u0086\u000e¢\u0006\u000e\n\u0000\u001a\u0004\b\u0006\u0010\u0007\"\u0004\b\b\u0010\tR\u0014\u0010\n\u001a\b\u0012\u0004\u0012\u00020\f0\u000bX\u0082\u0004¢\u0006\u0002\n\u0000¨\u0006\u001a"}, m14357d2 = {"Lcom/discord/tti_manager/TTIMetrics;", "", "()V", "<set-?>", "", "loggedTTI", "getLoggedTTI", "()Z", "setLoggedTTI", "(Z)V", "timings", "", "Lcom/discord/tti_manager/TTIMetrics$Timing;", "getTimings", "Ljava/util/ArrayList;", "kotlin.jvm.PlatformType", "Lkotlin/collections/ArrayList;", "record", "", "label", "", "timestamp", "", "tag", "autoGenerated", NativeTimingSpec.NAME, "tti_manager_release"}, m14356k = 1, m14355mv = {1, 8, 0}, m14353xi = 48)
/* loaded from: /home/user/temp/discord/apk/extracted/_base.apk/classes3.dex */
public final class TTIMetrics {
    private static boolean loggedTTI;
    public static final TTIMetrics INSTANCE = new TTIMetrics();
    private static final List<Timing> timings = new ArrayList();

    @Metadata(m14358d1 = {"\u0000(\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\t\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0002\b\u0010\n\u0002\u0010\b\n\u0002\b\u0002\b\u0086\b\u0018\u00002\u00020\u0001B'\u0012\u0006\u0010\u0002\u001a\u00020\u0003\u0012\u0006\u0010\u0004\u001a\u00020\u0005\u0012\b\u0010\u0006\u001a\u0004\u0018\u00010\u0003\u0012\u0006\u0010\u0007\u001a\u00020\b¢\u0006\u0002\u0010\tJ\t\u0010\u0011\u001a\u00020\u0003HÆ\u0003J\t\u0010\u0012\u001a\u00020\u0005HÆ\u0003J\u000b\u0010\u0013\u001a\u0004\u0018\u00010\u0003HÆ\u0003J\t\u0010\u0014\u001a\u00020\bHÆ\u0003J3\u0010\u0015\u001a\u00020\u00002\b\b\u0002\u0010\u0002\u001a\u00020\u00032\b\b\u0002\u0010\u0004\u001a\u00020\u00052\n\b\u0002\u0010\u0006\u001a\u0004\u0018\u00010\u00032\b\b\u0002\u0010\u0007\u001a\u00020\bHÆ\u0001J\u0013\u0010\u0016\u001a\u00020\b2\b\u0010\u0017\u001a\u0004\u0018\u00010\u0001HÖ\u0003J\t\u0010\u0018\u001a\u00020\u0019HÖ\u0001J\t\u0010\u001a\u001a\u00020\u0003HÖ\u0001R\u0011\u0010\u0007\u001a\u00020\b¢\u0006\b\n\u0000\u001a\u0004\b\n\u0010\u000bR\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\f\u0010\rR\u0013\u0010\u0006\u001a\u0004\u0018\u00010\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u000e\u0010\rR\u0011\u0010\u0004\u001a\u00020\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u000f\u0010\u0010¨\u0006\u001b"}, m14357d2 = {"Lcom/discord/tti_manager/TTIMetrics$Timing;", "", "label", "", "timestamp", "", "tag", "autoGenerated", "", "(Ljava/lang/String;JLjava/lang/String;Z)V", "getAutoGenerated", "()Z", "getLabel", "()Ljava/lang/String;", "getTag", "getTimestamp", "()J", "component1", "component2", "component3", "component4", "copy", "equals", "other", "hashCode", "", "toString", "tti_manager_release"}, m14356k = 1, m14355mv = {1, 8, 0}, m14353xi = 48)
    /* loaded from: /home/user/temp/discord/apk/extracted/_base.apk/classes3.dex */
    public static final class Timing {
        private final boolean autoGenerated;
        private final String label;
        private final String tag;
        private final long timestamp;

        public Timing(String label, long j, String str, boolean z) {
            C9612q.m13917h(label, "label");
            this.label = label;
            this.timestamp = j;
            this.tag = str;
            this.autoGenerated = z;
        }

        public static /* synthetic */ Timing copy$default(Timing timing, String str, long j, String str2, boolean z, int i, Object obj) {
            if ((i & 1) != 0) {
                str = timing.label;
            }
            if ((i & 2) != 0) {
                j = timing.timestamp;
            }
            long j2 = j;
            if ((i & 4) != 0) {
                str2 = timing.tag;
            }
            String str3 = str2;
            if ((i & 8) != 0) {
                z = timing.autoGenerated;
            }
            return timing.copy(str, j2, str3, z);
        }

        public final String component1() {
            return this.label;
        }

        public final long component2() {
            return this.timestamp;
        }

        public final String component3() {
            return this.tag;
        }

        public final boolean component4() {
            return this.autoGenerated;
        }

        public final Timing copy(String label, long j, String str, boolean z) {
            C9612q.m13917h(label, "label");
            return new Timing(label, j, str, z);
        }

        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj instanceof Timing) {
                Timing timing = (Timing) obj;
                return C9612q.m13922c(this.label, timing.label) && this.timestamp == timing.timestamp && C9612q.m13922c(this.tag, timing.tag) && this.autoGenerated == timing.autoGenerated;
            }
            return false;
        }

        public final boolean getAutoGenerated() {
            return this.autoGenerated;
        }

        public final String getLabel() {
            return this.label;
        }

        public final String getTag() {
            return this.tag;
        }

        public final long getTimestamp() {
            return this.timestamp;
        }

        /* JADX WARN: Multi-variable type inference failed */
        public int hashCode() {
            int hashCode = ((this.label.hashCode() * 31) + C2689b.m32716a(this.timestamp)) * 31;
            String str = this.tag;
            int hashCode2 = (hashCode + (str == null ? 0 : str.hashCode())) * 31;
            boolean z = this.autoGenerated;
            int i = z;
            if (z != 0) {
                i = 1;
            }
            return hashCode2 + i;
        }

        public String toString() {
            String str = this.label;
            long j = this.timestamp;
            String str2 = this.tag;
            boolean z = this.autoGenerated;
            return "Timing(label=" + str + ", timestamp=" + j + ", tag=" + str2 + ", autoGenerated=" + z + ")";
        }
    }

    private TTIMetrics() {
    }

    public static /* synthetic */ void record$default(TTIMetrics tTIMetrics, String str, long j, String str2, boolean z, int i, Object obj) {
        if ((i & 2) != 0) {
            j = System.currentTimeMillis();
        }
        long j2 = j;
        if ((i & 4) != 0) {
            str2 = null;
        }
        String str3 = str2;
        if ((i & 8) != 0) {
            z = false;
        }
        tTIMetrics.record(str, j2, str3, z);
    }

    public final synchronized boolean getLoggedTTI() {
        return loggedTTI;
    }

    public final synchronized ArrayList<Timing> getTimings() {
        return new ArrayList<>(timings);
    }

    public final synchronized void record(String label, long j, String str, boolean z) {
        C9612q.m13917h(label, "label");
        timings.add(new Timing(label, j, str, z));
    }

    public final synchronized void setLoggedTTI(boolean z) {
        loggedTTI = z;
    }
}
